hw 06
Svyatoslav29/nodejs-homework-rest-api pull request #5
Opened 2022-01-24 20:06 UTC by Svyatoslav29

Доброго времени суток, 6дз

2022-01-25 21:10 UTC, KirillKulakow commented on model/user.js
> +    default: randomUUID()
у всех юзеров будет одинаковый токен - исправить

2022-01-25 21:10 UTC, KirillKulakow requested changes
Need fix

2022-01-27 18:37 UTC, Svyatoslav29 commented on model/user.js
> +    default: randomUUID()
Добрый вечер, переделано

2022-01-27 20:20 UTC, KirillKulakow approved these changes

2022-01-31 21:01 UTC, merged